#!/usr/bin/env php
<?php

$container = require __DIR__ . '/app/bootstrap.php';
$app = new Silly\Application();

$app->useContainer($container, $injectWithTypeHint = true);
$app->command('uri-parse [uri]', 'UriParser\Command\UriParseCommand');

$app->run();
